### ISSUE TITLE
Handle multiple slot command

### ISSUE THREAD

**Issue by Torbraw** [Torbraw/DBot#32]
Add a new collection somewhere (in client?) to keep track of each slot command by channel. If there's already 1 command running in that channel, don't process the command.

**Comment by MaxGendron** [comment]
Not finished, need to wait on a change on Commando to be able to have access to the throttle of the command to reset it.
Right now, when we abort the command when there's another one running, the throttle being consumed which we do not want.

**Comment by Torbraw** [comment]
Discordjs v13 seems to be able to handle that, closing it
